-- Wireshark dissector for the Forest ebike CAN bus.
--
-- GENERATED by bikecan/wireshark.py from dbc/signals.toml. Do not edit this
-- file: the evidence for every claim lives in the TOML, and hand-editing here
-- loses it. Regenerate with:
--
--     uv run python -m bikecan.wireshark
--
-- USAGE
--   Wireshark reads candump logs directly, so no conversion is needed:
--
--     tshark -X lua_script:dbc/ebike.lua -r data/sessions/<session>/can0.log
--
--   For the GUI, copy or symlink this file into the personal plugin folder
--   (Help > About Wireshark > Folders shows where; usually
--   ~/.local/lib/wireshark/plugins on Linux, ~/.config/wireshark/plugins on
--   macOS) and reload with Analyze > Reload Lua Plugins.
--
-- CONFIDENCE
--   Signals below "confirmed" show their level beside the value. A value with
--   no marker is tied to a measurement or a commanded action; one marked
--   [probable] or [hypothesis] is not. Read dbc/signals.toml for the evidence.

local ebike = Proto("ebike", "Forest ebike CAN")

local can_id = Field.new("can.id")
local can_extended = Field.new("can.flags.xtd")

-- The message name, so that every message can be filtered by the name it
-- displays and not just by its identifier. Generated rather than read from the
-- payload: the name is ours, not the bus's.
local f_message = ProtoField.string("ebike.message", "Message")

-- Read `length` bits starting at MSB-first bit index `start`: bit 0 is the top
-- bit of byte 0, which is how signals.toml numbers big_endian signals and how
-- discover.bit_detail() prints them.
local function be(tvb, start, length, signed)
  local first = math.floor(start / 8)
  local last = math.floor((start + length - 1) / 8)
  local value = tvb(first, last - first + 1):bitfield(start - first * 8, length)
  if signed then
    local half = 2 ^ (length - 1)
    if value >= half then
      value = value - 2 * half
    end
  end
  return value
end

-- Read `count` bytes at `first`, least significant byte first.
local function le(tvb, first, count, signed)
  local range = tvb(first, count)
  if signed then
    return range:le_int()
  end
  return range:le_uint()
end


-- Signals. The evidence for each is in dbc/signals.toml.
-- HeadLight_3606.HeadLightOn: Byte 1. Goes to 1 within 0.77 s of the HLON command and to 0 within 0.33 s of HLOFF, then to 1 a
local f_headlight_3606_headlighton = ProtoField.uint32("ebike.headlight_3606.headlighton", "HeadLightOn", base.DEC)
-- HeadLight_3606.BusAwake: Byte 0. 1 = the bike is awake, 2 = asleep. Bytes 3 and 5 carry the same fact inverted: b0=1 goes
local f_headlight_3606_busawake = ProtoField.uint32("ebike.headlight_3606.busawake", "BusAwake", base.DEC)
-- RearLight_1606.RearLightOn: Byte 4. Goes to 1 within 0.76 s of RLONEN and to 0 within 0.40 s of RLOFF, and also tracks UNLOC
local f_rearlight_1606_rearlighton = ProtoField.uint32("ebike.rearlight_1606.rearlighton", "RearLightOn", base.DEC)
-- RearLight_1606.BusAwake: Byte 0. 1 = the bike is awake, 0 = asleep. The same fact that byte 0 of 02203606 carries, in the
local f_rearlight_1606_busawake = ProtoField.uint32("ebike.rearlight_1606.busawake", "BusAwake", base.DEC)
-- RearLight_1606.MaxSpeed: CORRECTION -- this signal was called RearLightAwakeLevel and read as a brightness percentage. It
local f_rearlight_1606_maxspeed = ProtoField.uint32("ebike.rearlight_1606.maxspeed", "MaxSpeed", base.DEC)
-- Lock_6400.Unlocked: Byte 0. 1 = unlocked, 0 = locked -- note this is the inverse of GTFRI's ECU Lock State field, so
local f_lock_6400_unlocked = ProtoField.uint32("ebike.lock_6400.unlocked", "Unlocked", base.DEC)
-- SpeedLimit_1600.MaxSpeed: CONFIRMED -- tied to a commanded action, six times in one session. The set-speed-while-unlocked 
local f_speedlimit_1600_maxspeed = ProtoField.uint32("ebike.speedlimit_1600.maxspeed", "MaxSpeed", base.DEC)
-- BmsCellVoltages_1_4.Cell1: Little-endian uint16 in mV: bytes 14 10 read as 0x1014 = 4116 mV.
local f_bmscellvoltages_1_4_cell1 = ProtoField.uint32("ebike.bmscellvoltages_1_4.cell1", "Cell1", base.DEC)
-- BmsCellVoltages_1_4.Cell2: Little-endian uint16 in mV.
local f_bmscellvoltages_1_4_cell2 = ProtoField.uint32("ebike.bmscellvoltages_1_4.cell2", "Cell2", base.DEC)
-- BmsCellVoltages_1_4.Cell3: Little-endian uint16 in mV.
local f_bmscellvoltages_1_4_cell3 = ProtoField.uint32("ebike.bmscellvoltages_1_4.cell3", "Cell3", base.DEC)
-- BmsCellVoltages_1_4.Cell4: Little-endian uint16 in mV.
local f_bmscellvoltages_1_4_cell4 = ProtoField.uint32("ebike.bmscellvoltages_1_4.cell4", "Cell4", base.DEC)
-- BmsCellVoltages_5_8.Cell5: Little-endian uint16 in mV.
local f_bmscellvoltages_5_8_cell5 = ProtoField.uint32("ebike.bmscellvoltages_5_8.cell5", "Cell5", base.DEC)
-- BmsCellVoltages_5_8.Cell6: Little-endian uint16 in mV.
local f_bmscellvoltages_5_8_cell6 = ProtoField.uint32("ebike.bmscellvoltages_5_8.cell6", "Cell6", base.DEC)
-- BmsCellVoltages_5_8.Cell7: Little-endian uint16 in mV.
local f_bmscellvoltages_5_8_cell7 = ProtoField.uint32("ebike.bmscellvoltages_5_8.cell7", "Cell7", base.DEC)
-- BmsCellVoltages_5_8.Cell8: Little-endian uint16 in mV.
local f_bmscellvoltages_5_8_cell8 = ProtoField.uint32("ebike.bmscellvoltages_5_8.cell8", "Cell8", base.DEC)
-- BmsCellVoltages_9_12.Cell9: Little-endian uint16 in mV.
local f_bmscellvoltages_9_12_cell9 = ProtoField.uint32("ebike.bmscellvoltages_9_12.cell9", "Cell9", base.DEC)
-- BmsCellVoltages_9_12.Cell10: Little-endian uint16 in mV.
local f_bmscellvoltages_9_12_cell10 = ProtoField.uint32("ebike.bmscellvoltages_9_12.cell10", "Cell10", base.DEC)
-- BmsCellVoltages_9_12.Cell11: Little-endian uint16 in mV.
local f_bmscellvoltages_9_12_cell11 = ProtoField.uint32("ebike.bmscellvoltages_9_12.cell11", "Cell11", base.DEC)
-- BmsCellVoltages_9_12.Cell12: Little-endian uint16 in mV.
local f_bmscellvoltages_9_12_cell12 = ProtoField.uint32("ebike.bmscellvoltages_9_12.cell12", "Cell12", base.DEC)
-- BmsCellVoltage_13.Cell13: Little-endian uint16 in mV. Bytes 2-7 are always zero: only 13 cells.
local f_bmscellvoltage_13_cell13 = ProtoField.uint32("ebike.bmscellvoltage_13.cell13", "Cell13", base.DEC)
-- BmsCellTemperatures.CellTemp1: Was Temp1. Cell sensor 1: 05124615 names it (index 1) as the sensor holding the cell maximum in 
local f_bmscelltemperatures_celltemp1 = ProtoField.uint32("ebike.bmscelltemperatures.celltemp1", "CellTemp1", base.DEC)
-- BmsCellTemperatures.CellTemp2: Was Temp2. Cell sensor 2 by position between the two that 05124615 indexes. Never itself named a
local f_bmscelltemperatures_celltemp2 = ProtoField.uint32("ebike.bmscelltemperatures.celltemp2", "CellTemp2", base.DEC)
-- BmsCellTemperatures.CellTemp3: Was Temp3. Cell sensor 3: 05124615 names it (index 3) as the cell minimum whenever the minimum d
local f_bmscelltemperatures_celltemp3 = ProtoField.uint32("ebike.bmscelltemperatures.celltemp3", "CellTemp3", base.DEC)
-- BmsTemperatures_B.Temp4: 0x1D = 29 degC. Probably the MOS temperature: matches <ECU Info> mos_temp_c in sessions 2, 3, 4 
local f_bmstemperatures_b_temp4 = ProtoField.uint32("ebike.bmstemperatures_b.temp4", "Temp4", base.DEC)
-- BmsTemperatures_B.Temp5: 0x1B = 27 degC, and the one temperature byte whose identity can be settled by elimination: it is
local f_bmstemperatures_b_temp5 = ProtoField.uint32("ebike.bmstemperatures_b.temp5", "Temp5", base.DEC)
-- BmsTemperatures_B.Temp6: 0x1C = 28 degC. Sensor identity unknown.
local f_bmstemperatures_b_temp6 = ProtoField.uint32("ebike.bmstemperatures_b.temp6", "Temp6", base.DEC)
-- BmsPackVoltageCurrent.PackVoltage: Bytes 0-3, big-endian, mV. 0x0000D176 = 53622 mV, which is exactly the sum of the 13 cell voltag
local f_bmspackvoltagecurrent_packvoltage = ProtoField.uint32("ebike.bmspackvoltagecurrent.packvoltage", "PackVoltage", base.DEC)
-- BmsPackVoltageCurrent.PackCurrent: Bytes 4-7, big-endian, SIGNED, mA. 0xFFFFFFA9 is -87 mA, not 4294967209. The sign is not an infe
local f_bmspackvoltagecurrent_packcurrent = ProtoField.int32("ebike.bmspackvoltagecurrent.packcurrent", "PackCurrent", base.DEC)
-- BmsChargeState.BmsReportMode: Byte 0 is 1 or 3. It is 1 on every 300 s poll reply while the bike is asleep and 3 within a seco
local f_bmschargestate_bmsreportmode = ProtoField.uint32("ebike.bmschargestate.bmsreportmode", "BmsReportMode", base.DEC)
-- BmsChargeState.StateOfCharge: Bytes 2-3, big-endian, 0.1 %. Confirmed against <Scooter Battery Percentage> in +RESP:GTFRI at f
local f_bmschargestate_stateofcharge = ProtoField.double("ebike.bmschargestate.stateofcharge", "StateOfCharge")
-- BmsChargeState.StateOfHealth: Bytes 4-5, big-endian, 0.1 %. Matches <Battery Status> group 2, which the @Track parser calls ba
local f_bmschargestate_stateofhealth = ProtoField.double("ebike.bmschargestate.stateofhealth", "StateOfHealth")
-- BmsChargeStatePolled.StateOfCharge: As 05FF4609.StateOfCharge; this is the frame the 88/99/100 % readings came from.
local f_bmschargestatepolled_stateofcharge = ProtoField.double("ebike.bmschargestatepolled.stateofcharge", "StateOfCharge")
-- BmsChargeStatePolled.StateOfHealth: As 05FF4609.StateOfHealth.
local f_bmschargestatepolled_stateofhealth = ProtoField.double("ebike.bmschargestatepolled.stateofhealth", "StateOfHealth")
-- BmsCellVoltages_1_4_Polled.Cell1: As 05FF4602.Cell1. 0B10 reads as 0x100B = 4107 mV.
local f_bmscellvoltages_1_4_polled_cell1 = ProtoField.uint32("ebike.bmscellvoltages_1_4_polled.cell1", "Cell1", base.DEC)
-- BmsCellVoltages_1_4_Polled.Cell2: As 05FF4602.Cell2.
local f_bmscellvoltages_1_4_polled_cell2 = ProtoField.uint32("ebike.bmscellvoltages_1_4_polled.cell2", "Cell2", base.DEC)
-- BmsCellVoltages_1_4_Polled.Cell3: As 05FF4602.Cell3.
local f_bmscellvoltages_1_4_polled_cell3 = ProtoField.uint32("ebike.bmscellvoltages_1_4_polled.cell3", "Cell3", base.DEC)
-- BmsCellVoltages_1_4_Polled.Cell4: As 05FF4602.Cell4.
local f_bmscellvoltages_1_4_polled_cell4 = ProtoField.uint32("ebike.bmscellvoltages_1_4_polled.cell4", "Cell4", base.DEC)
-- BmsCellVoltages_5_8_Polled.Cell5: As 05FF4603.Cell5.
local f_bmscellvoltages_5_8_polled_cell5 = ProtoField.uint32("ebike.bmscellvoltages_5_8_polled.cell5", "Cell5", base.DEC)
-- BmsCellVoltages_5_8_Polled.Cell6: As 05FF4603.Cell6.
local f_bmscellvoltages_5_8_polled_cell6 = ProtoField.uint32("ebike.bmscellvoltages_5_8_polled.cell6", "Cell6", base.DEC)
-- BmsCellVoltages_5_8_Polled.Cell7: As 05FF4603.Cell7.
local f_bmscellvoltages_5_8_polled_cell7 = ProtoField.uint32("ebike.bmscellvoltages_5_8_polled.cell7", "Cell7", base.DEC)
-- BmsCellVoltages_5_8_Polled.Cell8: As 05FF4603.Cell8.
local f_bmscellvoltages_5_8_polled_cell8 = ProtoField.uint32("ebike.bmscellvoltages_5_8_polled.cell8", "Cell8", base.DEC)
-- BmsCellVoltages_9_12_Polled.Cell9: As 05FF4604.Cell9.
local f_bmscellvoltages_9_12_polled_cell9 = ProtoField.uint32("ebike.bmscellvoltages_9_12_polled.cell9", "Cell9", base.DEC)
-- BmsCellVoltages_9_12_Polled.Cell10: As 05FF4604.Cell10.
local f_bmscellvoltages_9_12_polled_cell10 = ProtoField.uint32("ebike.bmscellvoltages_9_12_polled.cell10", "Cell10", base.DEC)
-- BmsCellVoltages_9_12_Polled.Cell11: As 05FF4604.Cell11.
local f_bmscellvoltages_9_12_polled_cell11 = ProtoField.uint32("ebike.bmscellvoltages_9_12_polled.cell11", "Cell11", base.DEC)
-- BmsCellVoltages_9_12_Polled.Cell12: As 05FF4604.Cell12.
local f_bmscellvoltages_9_12_polled_cell12 = ProtoField.uint32("ebike.bmscellvoltages_9_12_polled.cell12", "Cell12", base.DEC)
-- BmsCellVoltage_13_Polled.Cell13: As 05FF4605.Cell13.
local f_bmscellvoltage_13_polled_cell13 = ProtoField.uint32("ebike.bmscellvoltage_13_polled.cell13", "Cell13", base.DEC)
-- BmsTemperatures_A_Polled.CellTemp1: As 05FF4606.CellTemp1; the polled frames carry the same bytes as the unsolicited frame beside th
local f_bmstemperatures_a_polled_celltemp1 = ProtoField.uint32("ebike.bmstemperatures_a_polled.celltemp1", "CellTemp1", base.DEC)
-- BmsTemperatures_A_Polled.CellTemp2: As 05FF4606.CellTemp2.
local f_bmstemperatures_a_polled_celltemp2 = ProtoField.uint32("ebike.bmstemperatures_a_polled.celltemp2", "CellTemp2", base.DEC)
-- BmsTemperatures_A_Polled.CellTemp3: As 05FF4606.CellTemp3.
local f_bmstemperatures_a_polled_celltemp3 = ProtoField.uint32("ebike.bmstemperatures_a_polled.celltemp3", "CellTemp3", base.DEC)
-- BmsTemperatures_B_Polled.Temp4: As 05FF4607.Temp4.
local f_bmstemperatures_b_polled_temp4 = ProtoField.uint32("ebike.bmstemperatures_b_polled.temp4", "Temp4", base.DEC)
-- BmsTemperatures_B_Polled.Temp5: As 05FF4607.Temp5.
local f_bmstemperatures_b_polled_temp5 = ProtoField.uint32("ebike.bmstemperatures_b_polled.temp5", "Temp5", base.DEC)
-- BmsTemperatures_B_Polled.Temp6: As 05FF4607.Temp6.
local f_bmstemperatures_b_polled_temp6 = ProtoField.uint32("ebike.bmstemperatures_b_polled.temp6", "Temp6", base.DEC)
-- BmsPackVoltageCurrentPolled.PackVoltage: As 05FF4610.PackVoltage. 0x0000D0E3 = 53475 mV.
local f_bmspackvoltagecurrentpolled_packvoltage = ProtoField.uint32("ebike.bmspackvoltagecurrentpolled.packvoltage", "PackVoltage", base.DEC)
-- BmsPackVoltageCurrentPolled.PackCurrent: As 05FF4610.PackCurrent -- big-endian, SIGNED, mA. 0xFFFFFFC4 is -60 mA, and +RESP:GTFRI reporte
local f_bmspackvoltagecurrentpolled_packcurrent = ProtoField.int32("ebike.bmspackvoltagecurrentpolled.packcurrent", "PackCurrent", base.DEC)
-- Node75HardwareVersion.HardwareVersion: Bytes 0-3 = 0x000000F4 = 244, constant across all 13 frames.
local f_node75hardwareversion_hardwareversion = ProtoField.uint32("ebike.node75hardwareversion.hardwareversion", "HardwareVersion", base.DEC)
-- Node75FirmwareVersion.FirmwareVersion: Bytes 0-3 = 0x00000015 = 21, constant across all 13 frames.
local f_node75firmwareversion_firmwareversion = ProtoField.uint32("ebike.node75firmwareversion.firmwareversion", "FirmwareVersion", base.DEC)
-- BmsCellExtremes.MaxCellVoltage: Bytes 0-1 big-endian. 4130, 4127 and 4125 mV, each the true maximum of the 13 cells.
local f_bmscellextremes_maxcellvoltage = ProtoField.uint32("ebike.bmscellextremes.maxcellvoltage", "MaxCellVoltage", base.DEC)
-- BmsCellExtremes.MaxCellIndex: Byte 2. Always 11 so far, and cell index 11 was in fact the highest in all 8 frames.
local f_bmscellextremes_maxcellindex = ProtoField.uint32("ebike.bmscellextremes.maxcellindex", "MaxCellIndex", base.DEC)
-- BmsCellExtremes.MinCellVoltage: Bytes 3-4 big-endian. 4116, 4114, 4113 and 4112 mV, each the true minimum.
local f_bmscellextremes_mincellvoltage = ProtoField.uint32("ebike.bmscellextremes.mincellvoltage", "MinCellVoltage", base.DEC)
-- BmsCellExtremes.MinCellIndex: Byte 5. Always 0, and cell index 0 was in fact the lowest in all 8 frames.
local f_bmscellextremes_mincellindex = ProtoField.uint32("ebike.bmscellextremes.mincellindex", "MinCellIndex", base.DEC)
-- BmsCellExtremes.CellVoltageSpread: Bytes 6-7 big-endian. Equal to MaxCellVoltage - MinCellVoltage in all 8 frames: 14, 14, 13 mV. R
local f_bmscellextremes_cellvoltagespread = ProtoField.uint32("ebike.bmscellextremes.cellvoltagespread", "CellVoltageSpread", base.DEC)
-- BmsCapacity.StateOfHealth: Bytes 0-1 big-endian, whole percent. 0x0061 = 97, matching <Battery Status> battery_health_pct i
local f_bmscapacity_stateofhealth = ProtoField.uint32("ebike.bmscapacity.stateofhealth", "StateOfHealth", base.DEC)
-- BmsCapacity.FullChargeCapacity: Bytes 2-3 big-endian, mAh. 0x368C = 13964, unchanged in all three sessions, which is what a full
local f_bmscapacity_fullchargecapacity = ProtoField.uint32("ebike.bmscapacity.fullchargecapacity", "FullChargeCapacity", base.DEC)
-- BmsCapacity.RemainingCapacity: Bytes 4-7 big-endian, mAh. 13771 -> 13747 -> 13736 across the three sessions, falling monotonica
local f_bmscapacity_remainingcapacity = ProtoField.uint32("ebike.bmscapacity.remainingcapacity", "RemainingCapacity", base.DEC)
-- BmsConfig.CellCount: Byte 0 = 13. Agrees with the cell count +RESP:GTBMI reports and with the number of cell voltage 
local f_bmsconfig_cellcount = ProtoField.uint32("ebike.bmsconfig.cellcount", "CellCount", base.DEC)
-- BmsTempExtremes.MaxTemp: Byte 0. Equals 05FF4606's byte at MaxTempIndex in 12/12 frames: 28, 29, 30 across sessions.
local f_bmstempextremes_maxtemp = ProtoField.uint32("ebike.bmstempextremes.maxtemp", "MaxTemp", base.DEC)
-- BmsTempExtremes.MaxTempIndex: Byte 1, 1-based index into 05FF4606. Always 1 so far, and 05FF4606 byte 0 was in fact a maximum 
local f_bmstempextremes_maxtempindex = ProtoField.uint32("ebike.bmstempextremes.maxtempindex", "MaxTempIndex", base.DEC)
-- BmsTempExtremes.MinTemp: Byte 2. Equals 05FF4606's byte at MinTempIndex in 12/12 frames: 28, 29, 30.
local f_bmstempextremes_mintemp = ProtoField.uint32("ebike.bmstempextremes.mintemp", "MinTemp", base.DEC)
-- BmsTempExtremes.MinTempIndex: Byte 3, 1-based index into 05FF4606. Reads 1 when all three cell sensors agree and 3 when they d
local f_bmstempextremes_mintempindex = ProtoField.uint32("ebike.bmstempextremes.mintempindex", "MinTempIndex", base.DEC)
-- Node15HardwareVersion.HardwareVersion: Bytes 0-3 = 0x000000C3. Appears as the first group of the serial's hardware version.
local f_node15hardwareversion_hardwareversion = ProtoField.uint32("ebike.node15hardwareversion.hardwareversion", "HardwareVersion", base.DEC)
-- Node15FirmwareVersion.FirmwareVersion: Bytes 0-3 = 0x0000004A. Appears as the first group of the serial's firmware version.
local f_node15firmwareversion_firmwareversion = ProtoField.uint32("ebike.node15firmwareversion.firmwareversion", "FirmwareVersion", base.DEC)
-- Node35HardwareVersion.HardwareVersion: Bytes 0-3 = 0x000000EB. Appears as the second group of the serial's hardware version.
local f_node35hardwareversion_hardwareversion = ProtoField.uint32("ebike.node35hardwareversion.hardwareversion", "HardwareVersion", base.DEC)
-- Node35FirmwareVersion.FirmwareVersion: Bytes 0-3 = 0x00000004. Appears as the second group of the serial's firmware version.
local f_node35firmwareversion_firmwareversion = ProtoField.uint32("ebike.node35firmwareversion.firmwareversion", "FirmwareVersion", base.DEC)
-- Node45HardwareVersion.HardwareVersion: Bytes 0-1 = 0x0500, the leading half of the serial's third hardware group.
local f_node45hardwareversion_hardwareversion = ProtoField.uint32("ebike.node45hardwareversion.hardwareversion", "HardwareVersion", base.DEC)
-- Node45FirmwareVersion.FirmwareVersion: Bytes 0-1 = 0x0103, the leading half of the serial's third firmware group.
local f_node45firmwareversion_firmwareversion = ProtoField.uint32("ebike.node45firmwareversion.firmwareversion", "FirmwareVersion", base.DEC)
-- Uptime_3400.Uptime: CONFIRMED -- the rate. In the 4 September corpus the field's change between consecutive frames e
local f_uptime_3400_uptime = ProtoField.uint32("ebike.uptime_3400.uptime", "Uptime", base.DEC)
-- AwakeTime_2400.AwakeTime: Bytes 0-1, LITTLE-endian, 10 s per count. C503 reads as 0x03C5 = 965, and the five frames of ses
local f_awaketime_2400_awaketime = ProtoField.uint32("ebike.awaketime_2400.awaketime", "AwakeTime", base.DEC)
-- AwakeTime_1400.AwakeTime: Bytes 0-3 big-endian, 10 s per count. 0x0000000A = 10. Runs 0-3 in session 1, 4-11 in session 2,
local f_awaketime_1400_awaketime = ProtoField.uint32("ebike.awaketime_1400.awaketime", "AwakeTime", base.DEC)
-- BmsSequence_4400.Sequence: Bytes 0-3 big-endian. Steps by exactly +1 per frame in all 58 frames across seven sessions: 0-4,
local f_bmssequence_4400_sequence = ProtoField.uint32("ebike.bmssequence_4400.sequence", "Sequence", base.DEC)
-- Unknown_3604.AnalogueA: Bytes 0-1. Byte 0 has been zero in all 5892 frames recorded, so the width is a guess; 16 bits is
local f_unknown_3604_analoguea = ProtoField.uint32("ebike.unknown_3604.analoguea", "AnalogueA", base.DEC)
-- Unknown_3604.AnalogueB: Bytes 2-3. Stationary value 2 to 4, mean 3.05, uncorrelated with AnalogueA (r = 0.07) -- which i
local f_unknown_3604_analogueb = ProtoField.uint32("ebike.unknown_3604.analogueb", "AnalogueB", base.DEC)
-- Unknown_3604.Constant200: Bytes 4-5. Holds 200 (0xC8) in all but the first second after a wake, where it is 0, and in a 90
local f_unknown_3604_constant200 = ProtoField.uint32("ebike.unknown_3604.constant200", "Constant200", base.DEC)
-- Unknown_1603.VoltageLike: Bytes 0-3 big-endian. Seven distinct values across seven sessions, all within 0.3 % of the pack 
local f_unknown_1603_voltagelike = ProtoField.uint32("ebike.unknown_1603.voltagelike", "VoltageLike", base.DEC)
-- Heartbeat_1000.SystemReady: Bit 0x08 of byte 0. Clear for the first seconds after the pack is connected, then set, and it ne
local f_heartbeat_1000_systemready = ProtoField.uint32("ebike.heartbeat_1000.systemready", "SystemReady", base.DEC)

ebike.fields = {
  f_message,
  f_headlight_3606_headlighton,
  f_headlight_3606_busawake,
  f_rearlight_1606_rearlighton,
  f_rearlight_1606_busawake,
  f_rearlight_1606_maxspeed,
  f_lock_6400_unlocked,
  f_speedlimit_1600_maxspeed,
  f_bmscellvoltages_1_4_cell1,
  f_bmscellvoltages_1_4_cell2,
  f_bmscellvoltages_1_4_cell3,
  f_bmscellvoltages_1_4_cell4,
  f_bmscellvoltages_5_8_cell5,
  f_bmscellvoltages_5_8_cell6,
  f_bmscellvoltages_5_8_cell7,
  f_bmscellvoltages_5_8_cell8,
  f_bmscellvoltages_9_12_cell9,
  f_bmscellvoltages_9_12_cell10,
  f_bmscellvoltages_9_12_cell11,
  f_bmscellvoltages_9_12_cell12,
  f_bmscellvoltage_13_cell13,
  f_bmscelltemperatures_celltemp1,
  f_bmscelltemperatures_celltemp2,
  f_bmscelltemperatures_celltemp3,
  f_bmstemperatures_b_temp4,
  f_bmstemperatures_b_temp5,
  f_bmstemperatures_b_temp6,
  f_bmspackvoltagecurrent_packvoltage,
  f_bmspackvoltagecurrent_packcurrent,
  f_bmschargestate_bmsreportmode,
  f_bmschargestate_stateofcharge,
  f_bmschargestate_stateofhealth,
  f_bmschargestatepolled_stateofcharge,
  f_bmschargestatepolled_stateofhealth,
  f_bmscellvoltages_1_4_polled_cell1,
  f_bmscellvoltages_1_4_polled_cell2,
  f_bmscellvoltages_1_4_polled_cell3,
  f_bmscellvoltages_1_4_polled_cell4,
  f_bmscellvoltages_5_8_polled_cell5,
  f_bmscellvoltages_5_8_polled_cell6,
  f_bmscellvoltages_5_8_polled_cell7,
  f_bmscellvoltages_5_8_polled_cell8,
  f_bmscellvoltages_9_12_polled_cell9,
  f_bmscellvoltages_9_12_polled_cell10,
  f_bmscellvoltages_9_12_polled_cell11,
  f_bmscellvoltages_9_12_polled_cell12,
  f_bmscellvoltage_13_polled_cell13,
  f_bmstemperatures_a_polled_celltemp1,
  f_bmstemperatures_a_polled_celltemp2,
  f_bmstemperatures_a_polled_celltemp3,
  f_bmstemperatures_b_polled_temp4,
  f_bmstemperatures_b_polled_temp5,
  f_bmstemperatures_b_polled_temp6,
  f_bmspackvoltagecurrentpolled_packvoltage,
  f_bmspackvoltagecurrentpolled_packcurrent,
  f_node75hardwareversion_hardwareversion,
  f_node75firmwareversion_firmwareversion,
  f_bmscellextremes_maxcellvoltage,
  f_bmscellextremes_maxcellindex,
  f_bmscellextremes_mincellvoltage,
  f_bmscellextremes_mincellindex,
  f_bmscellextremes_cellvoltagespread,
  f_bmscapacity_stateofhealth,
  f_bmscapacity_fullchargecapacity,
  f_bmscapacity_remainingcapacity,
  f_bmsconfig_cellcount,
  f_bmstempextremes_maxtemp,
  f_bmstempextremes_maxtempindex,
  f_bmstempextremes_mintemp,
  f_bmstempextremes_mintempindex,
  f_node15hardwareversion_hardwareversion,
  f_node15firmwareversion_firmwareversion,
  f_node35hardwareversion_hardwareversion,
  f_node35firmwareversion_firmwareversion,
  f_node45hardwareversion_hardwareversion,
  f_node45firmwareversion_firmwareversion,
  f_uptime_3400_uptime,
  f_awaketime_2400_awaketime,
  f_awaketime_1400_awaketime,
  f_bmssequence_4400_sequence,
  f_unknown_3604_analoguea,
  f_unknown_3604_analogueb,
  f_unknown_3604_constant200,
  f_unknown_1603_voltagelike,
  f_heartbeat_1000_systemready,
}

local messages = {}

messages[0x02203606] = {
  name = "HeadLight_3606",
  extended = true,
  comment = "[confirmed] The headlight. Identified by remote command: the console logged HLON at 1788785214.368 and HLOFF at 1788785234.208, and this message changed 0.77 s ... (dbc/signals.toml)",
  signals = {
    {
      field = f_headlight_3606_headlighton,
      first = 1,
      count = 1,
      suffix = "",
      value = function(tvb) return be(tvb, 8, 8, false) end,
    },
    {
      field = f_headlight_3606_busawake,
      first = 0,
      count = 1,
      suffix = "",
      value = function(tvb) return be(tvb, 0, 8, false) end,
    },
  },
}

messages[0x02181606] = {
  name = "RearLight_1606",
  extended = true,
  comment = "[confirmed] The rear light. Same method as the headlight: RLONEN at 1788785392.364 and RLOFF at 1788785412.125, with this message changing 0.76 s and 0.40 s ... (dbc/signals.toml)",
  signals = {
    {
      field = f_rearlight_1606_rearlighton,
      first = 4,
      count = 1,
      suffix = "",
      value = function(tvb) return be(tvb, 32, 8, false) end,
    },
    {
      field = f_rearlight_1606_busawake,
      first = 0,
      count = 1,
      suffix = "",
      value = function(tvb) return be(tvb, 0, 8, false) end,
    },
    {
      field = f_rearlight_1606_maxspeed,
      first = 2,
      count = 1,
      suffix = " km/h",
      value = function(tvb) return be(tvb, 16, 8, false) end,
    },
  },
}

messages[0x13b76400] = {
  name = "Lock_6400",
  extended = true,
  comment = "[confirmed] The lock (immobiliser) reporting its state. A single-byte message, and the only one on the bus with priority 0x13. NOT PERIODIC. This carried ... (dbc/signals.toml)",
  signals = {
    {
      field = f_lock_6400_unlocked,
      first = 0,
      count = 1,
      suffix = "",
      value = function(tvb) return be(tvb, 0, 8, false) end,
    },
  },
}

messages[0x03ff1600] = {
  name = "SpeedLimit_1600",
  extended = true,
  comment = "[confirmed] The configured maximum assisted speed. Published at 1 Hz while the bike is awake and absent entirely while it is locked -- in the unlock/lock session ... (dbc/signals.toml)",
  signals = {
    {
      field = f_speedlimit_1600_maxspeed,
      first = 7,
      count = 1,
      suffix = " km/h",
      value = function(tvb) return be(tvb, 56, 8, false) end,
    },
  },
}

messages[0x05ff4602] = {
  name = "BmsCellVoltages_1_4",
  extended = true,
  comment = "[confirmed] BMS cell voltages, cells 1-4. Confirmed without guesswork: the +RESP:GTBMI report relays this frame's payload verbatim -- the identical byte string ... (dbc/signals.toml)",
  signals = {
    {
      field = f_bmscellvoltages_1_4_cell1,
      first = 0,
      count = 2,
      suffix = " mV",
      value = function(tvb) return le(tvb, 0, 2, false) end,
    },
    {
      field = f_bmscellvoltages_1_4_cell2,
      first = 2,
      count = 2,
      suffix = " mV",
      value = function(tvb) return le(tvb, 2, 2, false) end,
    },
    {
      field = f_bmscellvoltages_1_4_cell3,
      first = 4,
      count = 2,
      suffix = " mV",
      value = function(tvb) return le(tvb, 4, 2, false) end,
    },
    {
      field = f_bmscellvoltages_1_4_cell4,
      first = 6,
      count = 2,
      suffix = " mV",
      value = function(tvb) return le(tvb, 6, 2, false) end,
    },
  },
}

messages[0x05ff4603] = {
  name = "BmsCellVoltages_5_8",
  extended = true,
  comment = "[confirmed] BMS cell voltages, cells 5-8. Relayed verbatim in +RESP:GTBMI.",
  signals = {
    {
      field = f_bmscellvoltages_5_8_cell5,
      first = 0,
      count = 2,
      suffix = " mV",
      value = function(tvb) return le(tvb, 0, 2, false) end,
    },
    {
      field = f_bmscellvoltages_5_8_cell6,
      first = 2,
      count = 2,
      suffix = " mV",
      value = function(tvb) return le(tvb, 2, 2, false) end,
    },
    {
      field = f_bmscellvoltages_5_8_cell7,
      first = 4,
      count = 2,
      suffix = " mV",
      value = function(tvb) return le(tvb, 4, 2, false) end,
    },
    {
      field = f_bmscellvoltages_5_8_cell8,
      first = 6,
      count = 2,
      suffix = " mV",
      value = function(tvb) return le(tvb, 6, 2, false) end,
    },
  },
}

messages[0x05ff4604] = {
  name = "BmsCellVoltages_9_12",
  extended = true,
  comment = "[confirmed] BMS cell voltages, cells 9-12. Relayed verbatim in +RESP:GTBMI.",
  signals = {
    {
      field = f_bmscellvoltages_9_12_cell9,
      first = 0,
      count = 2,
      suffix = " mV",
      value = function(tvb) return le(tvb, 0, 2, false) end,
    },
    {
      field = f_bmscellvoltages_9_12_cell10,
      first = 2,
      count = 2,
      suffix = " mV",
      value = function(tvb) return le(tvb, 2, 2, false) end,
    },
    {
      field = f_bmscellvoltages_9_12_cell11,
      first = 4,
      count = 2,
      suffix = " mV",
      value = function(tvb) return le(tvb, 4, 2, false) end,
    },
    {
      field = f_bmscellvoltages_9_12_cell12,
      first = 6,
      count = 2,
      suffix = " mV",
      value = function(tvb) return le(tvb, 6, 2, false) end,
    },
  },
}

messages[0x05ff4605] = {
  name = "BmsCellVoltage_13",
  extended = true,
  comment = "[confirmed] BMS cell voltage, cell 13, then padding. This pack has 13 cells, so the last frame of the series carries one value and six zero bytes -- which is how ... (dbc/signals.toml)",
  signals = {
    {
      field = f_bmscellvoltage_13_cell13,
      first = 0,
      count = 2,
      suffix = " mV",
      value = function(tvb) return le(tvb, 0, 2, false) end,
    },
  },
}

messages[0x05ff4606] = {
  name = "BmsCellTemperatures",
  extended = true,
  comment = "[confirmed] BMS cell temperatures, three sensors. Was BmsTemperatures_A. Payload 1C1C1C reads as 28, 28, 28 degC, and the same byte string is relayed in ... (dbc/signals.toml)",
  signals = {
    {
      field = f_bmscelltemperatures_celltemp1,
      first = 0,
      count = 1,
      suffix = " degC",
      value = function(tvb) return be(tvb, 0, 8, false) end,
    },
    {
      field = f_bmscelltemperatures_celltemp2,
      first = 1,
      count = 1,
      suffix = " degC [probable]",
      value = function(tvb) return be(tvb, 8, 8, false) end,
    },
    {
      field = f_bmscelltemperatures_celltemp3,
      first = 2,
      count = 1,
      suffix = " degC",
      value = function(tvb) return be(tvb, 16, 8, false) end,
    },
  },
}

messages[0x05ff4607] = {
  name = "BmsTemperatures_B",
  extended = true,
  comment = "[probable] More BMS temperatures: 1D1B1C reads as 29, 27, 28 degC, and is likewise relayed verbatim in +RESP:GTBMI. The spread across the two frames is 27-29 ... (dbc/signals.toml)",
  signals = {
    {
      field = f_bmstemperatures_b_temp4,
      first = 0,
      count = 1,
      suffix = " degC [probable]",
      value = function(tvb) return be(tvb, 0, 8, false) end,
    },
    {
      field = f_bmstemperatures_b_temp5,
      first = 1,
      count = 1,
      suffix = " degC [probable]",
      value = function(tvb) return be(tvb, 8, 8, false) end,
    },
    {
      field = f_bmstemperatures_b_temp6,
      first = 2,
      count = 1,
      suffix = " degC [probable]",
      value = function(tvb) return be(tvb, 16, 8, false) end,
    },
  },
}

messages[0x05ff4610] = {
  name = "BmsPackVoltageCurrent",
  extended = true,
  comment = "[confirmed] The BMS reporting the pack terminals: voltage in bytes 0-3, current in bytes 4-7, both big-endian 32-bit, both at 273 ms. This was the \"273 ms, bytes ... (dbc/signals.toml)",
  signals = {
    {
      field = f_bmspackvoltagecurrent_packvoltage,
      first = 0,
      count = 4,
      suffix = " mV",
      value = function(tvb) return be(tvb, 0, 32, false) end,
    },
    {
      field = f_bmspackvoltagecurrent_packcurrent,
      first = 4,
      count = 4,
      suffix = " mA",
      value = function(tvb) return be(tvb, 32, 32, true) end,
    },
  },
}

messages[0x05ff4609] = {
  name = "BmsChargeState",
  extended = true,
  comment = "[confirmed] State of charge and state of health. The BMS sends this unsolicited at 1044 ms while the bike is awake; 05124609 is the identical payload returned ... (dbc/signals.toml)",
  signals = {
    {
      field = f_bmschargestate_bmsreportmode,
      first = 0,
      count = 1,
      suffix = " [hypothesis]",
      value = function(tvb) return be(tvb, 0, 8, false) end,
    },
    {
      field = f_bmschargestate_stateofcharge,
      first = 2,
      count = 2,
      suffix = " %",
      value = function(tvb) return be(tvb, 16, 16, false) * 0.1 end,
    },
    {
      field = f_bmschargestate_stateofhealth,
      first = 4,
      count = 2,
      suffix = " %",
      value = function(tvb) return be(tvb, 32, 16, false) * 0.1 end,
    },
  },
}

messages[0x05124609] = {
  name = "BmsChargeStatePolled",
  extended = true,
  comment = "[confirmed] The reply to the IoT module's 02294609 poll, with the same layout as 05FF4609. Sent every 300 s, and one of the five identifiers that survive on a ... (dbc/signals.toml)",
  signals = {
    {
      field = f_bmschargestatepolled_stateofcharge,
      first = 2,
      count = 2,
      suffix = " %",
      value = function(tvb) return be(tvb, 16, 16, false) * 0.1 end,
    },
    {
      field = f_bmschargestatepolled_stateofhealth,
      first = 4,
      count = 2,
      suffix = " %",
      value = function(tvb) return be(tvb, 32, 16, false) * 0.1 end,
    },
  },
}

messages[0x05124601] = {
  name = "BmsStatusFlagsPolled",
  extended = true,
  comment = "[hypothesis] Reply to 02294601. Payload 007300000000, identical to the unsolicited 05FF4601 and to the first block +RESP:GTBMI relays (0073000000000000 ... (dbc/signals.toml)",
  signals = {},
}

messages[0x05124602] = {
  name = "BmsCellVoltages_1_4_Polled",
  extended = true,
  comment = "[confirmed] Reply to 02294602. Cells 1-4, as 05FF4602. Relayed verbatim in +RESP:GTBMI.",
  signals = {
    {
      field = f_bmscellvoltages_1_4_polled_cell1,
      first = 0,
      count = 2,
      suffix = " mV",
      value = function(tvb) return le(tvb, 0, 2, false) end,
    },
    {
      field = f_bmscellvoltages_1_4_polled_cell2,
      first = 2,
      count = 2,
      suffix = " mV",
      value = function(tvb) return le(tvb, 2, 2, false) end,
    },
    {
      field = f_bmscellvoltages_1_4_polled_cell3,
      first = 4,
      count = 2,
      suffix = " mV",
      value = function(tvb) return le(tvb, 4, 2, false) end,
    },
    {
      field = f_bmscellvoltages_1_4_polled_cell4,
      first = 6,
      count = 2,
      suffix = " mV",
      value = function(tvb) return le(tvb, 6, 2, false) end,
    },
  },
}

messages[0x05124603] = {
  name = "BmsCellVoltages_5_8_Polled",
  extended = true,
  comment = "[confirmed] Reply to 02294603. Cells 5-8, as 05FF4603. Relayed verbatim in +RESP:GTBMI.",
  signals = {
    {
      field = f_bmscellvoltages_5_8_polled_cell5,
      first = 0,
      count = 2,
      suffix = " mV",
      value = function(tvb) return le(tvb, 0, 2, false) end,
    },
    {
      field = f_bmscellvoltages_5_8_polled_cell6,
      first = 2,
      count = 2,
      suffix = " mV",
      value = function(tvb) return le(tvb, 2, 2, false) end,
    },
    {
      field = f_bmscellvoltages_5_8_polled_cell7,
      first = 4,
      count = 2,
      suffix = " mV",
      value = function(tvb) return le(tvb, 4, 2, false) end,
    },
    {
      field = f_bmscellvoltages_5_8_polled_cell8,
      first = 6,
      count = 2,
      suffix = " mV",
      value = function(tvb) return le(tvb, 6, 2, false) end,
    },
  },
}

messages[0x05124604] = {
  name = "BmsCellVoltages_9_12_Polled",
  extended = true,
  comment = "[confirmed] Reply to 02294604. Cells 9-12, as 05FF4604. Relayed verbatim in +RESP:GTBMI.",
  signals = {
    {
      field = f_bmscellvoltages_9_12_polled_cell9,
      first = 0,
      count = 2,
      suffix = " mV",
      value = function(tvb) return le(tvb, 0, 2, false) end,
    },
    {
      field = f_bmscellvoltages_9_12_polled_cell10,
      first = 2,
      count = 2,
      suffix = " mV",
      value = function(tvb) return le(tvb, 2, 2, false) end,
    },
    {
      field = f_bmscellvoltages_9_12_polled_cell11,
      first = 4,
      count = 2,
      suffix = " mV",
      value = function(tvb) return le(tvb, 4, 2, false) end,
    },
    {
      field = f_bmscellvoltages_9_12_polled_cell12,
      first = 6,
      count = 2,
      suffix = " mV",
      value = function(tvb) return le(tvb, 6, 2, false) end,
    },
  },
}

messages[0x05124605] = {
  name = "BmsCellVoltage_13_Polled",
  extended = true,
  comment = "[confirmed] Reply to 02294605. Cell 13, as 05FF4605. Bytes 2-7 are padding.",
  signals = {
    {
      field = f_bmscellvoltage_13_polled_cell13,
      first = 0,
      count = 2,
      suffix = " mV",
      value = function(tvb) return le(tvb, 0, 2, false) end,
    },
  },
}

messages[0x05124606] = {
  name = "BmsTemperatures_A_Polled",
  extended = true,
  comment = "[probable] Reply to 02294606. As 05FF4606: 1E1E1D reads as 30, 30, 29 degC -- the three cell temperature sensors. See 05FF4606.",
  signals = {
    {
      field = f_bmstemperatures_a_polled_celltemp1,
      first = 0,
      count = 1,
      suffix = " degC",
      value = function(tvb) return be(tvb, 0, 8, false) end,
    },
    {
      field = f_bmstemperatures_a_polled_celltemp2,
      first = 1,
      count = 1,
      suffix = " degC [probable]",
      value = function(tvb) return be(tvb, 8, 8, false) end,
    },
    {
      field = f_bmstemperatures_a_polled_celltemp3,
      first = 2,
      count = 1,
      suffix = " degC",
      value = function(tvb) return be(tvb, 16, 8, false) end,
    },
  },
}

messages[0x05124607] = {
  name = "BmsTemperatures_B_Polled",
  extended = true,
  comment = "[probable] Reply to 02294607. As 05FF4607: 1E1D1D reads as 30, 29, 29 degC -- the non-cell sensors, byte 0 probably the MOS. See 05FF4607.",
  signals = {
    {
      field = f_bmstemperatures_b_polled_temp4,
      first = 0,
      count = 1,
      suffix = " degC [probable]",
      value = function(tvb) return be(tvb, 0, 8, false) end,
    },
    {
      field = f_bmstemperatures_b_polled_temp5,
      first = 1,
      count = 1,
      suffix = " degC [probable]",
      value = function(tvb) return be(tvb, 8, 8, false) end,
    },
    {
      field = f_bmstemperatures_b_polled_temp6,
      first = 2,
      count = 1,
      suffix = " degC [probable]",
      value = function(tvb) return be(tvb, 16, 8, false) end,
    },
  },
}

messages[0x05124610] = {
  name = "BmsPackVoltageCurrentPolled",
  extended = true,
  comment = "[confirmed] Reply to 02294610. The pack terminals, same layout as 05FF4610: voltage in bytes 0-3, current in bytes 4-7, both big-endian 32-bit, the current ... (dbc/signals.toml)",
  signals = {
    {
      field = f_bmspackvoltagecurrentpolled_packvoltage,
      first = 0,
      count = 4,
      suffix = " mV",
      value = function(tvb) return be(tvb, 0, 32, false) end,
    },
    {
      field = f_bmspackvoltagecurrentpolled_packcurrent,
      first = 4,
      count = 4,
      suffix = " mA",
      value = function(tvb) return be(tvb, 32, 32, true) end,
    },
  },
}

messages[0x08f97500] = {
  name = "Node75HardwareVersion",
  extended = true,
  comment = "[probable] Reply to 02417500, in a request/reply family that had never been seen: 02 41 75 xx -> 08 F9 75 xx. Both appeared for the first time in the 7 ... (dbc/signals.toml)",
  signals = {
    {
      field = f_node75hardwareversion_hardwareversion,
      first = 0,
      count = 4,
      suffix = " [probable]",
      value = function(tvb) return be(tvb, 0, 32, false) end,
    },
  },
}

messages[0x08f97501] = {
  name = "Node75FirmwareVersion",
  extended = true,
  comment = "[probable] Reply to 02417501. See 08F97500 for the family and the caveat.",
  signals = {
    {
      field = f_node75firmwareversion_firmwareversion,
      first = 0,
      count = 4,
      suffix = " [probable]",
      value = function(tvb) return be(tvb, 0, 32, false) end,
    },
  },
}

messages[0x05124614] = {
  name = "BmsCellExtremes",
  extended = true,
  comment = "[confirmed] Highest and lowest cell, with which cell each one is, and the spread between them. Returned on request (02294614) during the wake-up enumeration ... (dbc/signals.toml)",
  signals = {
    {
      field = f_bmscellextremes_maxcellvoltage,
      first = 0,
      count = 2,
      suffix = " mV",
      value = function(tvb) return be(tvb, 0, 16, false) end,
    },
    {
      field = f_bmscellextremes_maxcellindex,
      first = 2,
      count = 1,
      suffix = "",
      value = function(tvb) return be(tvb, 16, 8, false) end,
    },
    {
      field = f_bmscellextremes_mincellvoltage,
      first = 3,
      count = 2,
      suffix = " mV",
      value = function(tvb) return be(tvb, 24, 16, false) end,
    },
    {
      field = f_bmscellextremes_mincellindex,
      first = 5,
      count = 1,
      suffix = "",
      value = function(tvb) return be(tvb, 40, 8, false) end,
    },
    {
      field = f_bmscellextremes_cellvoltagespread,
      first = 6,
      count = 2,
      suffix = " mV",
      value = function(tvb) return be(tvb, 48, 16, false) end,
    },
  },
}

messages[0x05124611] = {
  name = "BmsCapacity",
  extended = true,
  comment = "[confirmed] Pack capacity: how much charge the pack holds when full, and how much is left. Returned on request (02294611) during the wake-up enumeration ... (dbc/signals.toml)",
  signals = {
    {
      field = f_bmscapacity_stateofhealth,
      first = 0,
      count = 2,
      suffix = " %",
      value = function(tvb) return be(tvb, 0, 16, false) end,
    },
    {
      field = f_bmscapacity_fullchargecapacity,
      first = 2,
      count = 2,
      suffix = " mAh",
      value = function(tvb) return be(tvb, 16, 16, false) end,
    },
    {
      field = f_bmscapacity_remainingcapacity,
      first = 4,
      count = 4,
      suffix = " mAh",
      value = function(tvb) return be(tvb, 32, 32, false) end,
    },
  },
}

messages[0x05ff4600] = {
  name = "BmsConfig",
  extended = true,
  comment = "[probable] Payload 0D0300900303, unchanged in every session. Byte 0 is 0x0D = 13, the number of cells -- which +RESP:GTBMI states independently and which ... (dbc/signals.toml)",
  signals = {
    {
      field = f_bmsconfig_cellcount,
      first = 0,
      count = 1,
      suffix = " [probable]",
      value = function(tvb) return be(tvb, 0, 8, false) end,
    },
  },
}

messages[0x05124615] = {
  name = "BmsTempExtremes",
  extended = true,
  comment = "[confirmed] Highest and lowest temperature with sensor indices, by exact analogy with 05124614's treatment of the cell voltages. Returned on request (02294615) ... (dbc/signals.toml)",
  signals = {
    {
      field = f_bmstempextremes_maxtemp,
      first = 0,
      count = 1,
      suffix = " degC",
      value = function(tvb) return be(tvb, 0, 8, false) end,
    },
    {
      field = f_bmstempextremes_maxtempindex,
      first = 1,
      count = 1,
      suffix = "",
      value = function(tvb) return be(tvb, 8, 8, false) end,
    },
    {
      field = f_bmstempextremes_mintemp,
      first = 2,
      count = 1,
      suffix = " degC",
      value = function(tvb) return be(tvb, 16, 8, false) end,
    },
    {
      field = f_bmstempextremes_mintempindex,
      first = 3,
      count = 1,
      suffix = "",
      value = function(tvb) return be(tvb, 24, 8, false) end,
    },
  },
}

messages[0x03ff1500] = {
  name = "Node15HardwareVersion",
  extended = true,
  comment = "[confirmed] Reply to 02191500. 0x000000C3 = group 1 of <ECU Info> <Hardware Version>, verbatim.",
  signals = {
    {
      field = f_node15hardwareversion_hardwareversion,
      first = 0,
      count = 4,
      suffix = "",
      value = function(tvb) return be(tvb, 0, 32, false) end,
    },
  },
}

messages[0x03ff1501] = {
  name = "Node15FirmwareVersion",
  extended = true,
  comment = "[confirmed] Reply to 02191501. 0x0000004A = group 1 of <ECU Info> <Firmware Version>, verbatim.",
  signals = {
    {
      field = f_node15firmwareversion_firmwareversion,
      first = 0,
      count = 4,
      suffix = "",
      value = function(tvb) return be(tvb, 0, 32, false) end,
    },
  },
}

messages[0x04f93500] = {
  name = "Node35HardwareVersion",
  extended = true,
  comment = "[confirmed] Reply to 02213500. 0x000000EB = group 2 of <ECU Info> <Hardware Version>, verbatim.",
  signals = {
    {
      field = f_node35hardwareversion_hardwareversion,
      first = 0,
      count = 4,
      suffix = "",
      value = function(tvb) return be(tvb, 0, 32, false) end,
    },
  },
}

messages[0x04f93501] = {
  name = "Node35FirmwareVersion",
  extended = true,
  comment = "[confirmed] Reply to 02213501. 0x00000004 = group 2 of <ECU Info> <Firmware Version>, verbatim.",
  signals = {
    {
      field = f_node35firmwareversion_firmwareversion,
      first = 0,
      count = 4,
      suffix = "",
      value = function(tvb) return be(tvb, 0, 32, false) end,
    },
  },
}

messages[0x05124500] = {
  name = "Node45HardwareVersion",
  extended = true,
  comment = "[confirmed] Reply to 02294500. 0x0500 = group 3 of <ECU Info> <Hardware Version>, which the report writes as 05000000 -- these two bytes zero-extended. AA=45 is ... (dbc/signals.toml)",
  signals = {
    {
      field = f_node45hardwareversion_hardwareversion,
      first = 0,
      count = 2,
      suffix = "",
      value = function(tvb) return be(tvb, 0, 16, false) end,
    },
  },
}

messages[0x05124501] = {
  name = "Node45FirmwareVersion",
  extended = true,
  comment = "[confirmed] Reply to 02294501. 0x0103 = group 3 of <ECU Info> <Firmware Version>, written 01030000 in the report.",
  signals = {
    {
      field = f_node45firmwareversion_firmwareversion,
      first = 0,
      count = 2,
      suffix = "",
      value = function(tvb) return be(tvb, 0, 16, false) end,
    },
  },
}

messages[0x05124502] = {
  name = "BmsModelString",
  extended = true,
  comment = "[confirmed] The battery pack's model string in ASCII: 5250313353333541 is \"RP13S35A\". Reply to 02294502, at the BMS identity address. No signals are defined ... (dbc/signals.toml)",
  signals = {},
}

messages[0x05124503] = {
  name = "BmsManufactureInfo",
  extended = true,
  comment = "[hypothesis] Reply to 02294503, unchanged in every session: 00150C0900000C62. Bytes 1-3 are 0x15 0x0C 0x09 = 21, 12, 9, which reads as a manufacture date of 9 ... (dbc/signals.toml)",
  signals = {},
}

messages[0x04ff3400] = {
  name = "Uptime_3400",
  extended = true,
  comment = "[confirmed] A 10-second uptime tick. Bytes 0-1 and 4-7 are always zero; bytes 2-3 rise monotonically and never repeat, so every frame of this message is unique.",
  signals = {
    {
      field = f_uptime_3400_uptime,
      first = 2,
      count = 2,
      suffix = " s",
      value = function(tvb) return be(tvb, 16, 16, false) * 10 end,
    },
  },
}

messages[0x02f82400] = {
  name = "AwakeTime_2400",
  extended = true,
  comment = "[confirmed] A second 10-second counter, at AA=24, and NOT the same quantity as 04FF3400. This one counts only the time the bus spends awake. Proved by the sleep ... (dbc/signals.toml)",
  signals = {
    {
      field = f_awaketime_2400_awaketime,
      first = 0,
      count = 2,
      suffix = " s",
      value = function(tvb) return le(tvb, 0, 2, false) * 10 end,
    },
  },
}

messages[0x03ff1400] = {
  name = "AwakeTime_1400",
  extended = true,
  comment = "[confirmed] Cumulative awake time again, at AA=14, big-endian and 32 bits wide. Same quantity and same rate as 02F82400, different origin: it read 0 at the start ... (dbc/signals.toml)",
  signals = {
    {
      field = f_awaketime_1400_awaketime,
      first = 0,
      count = 4,
      suffix = " s",
      value = function(tvb) return be(tvb, 0, 32, false) * 10 end,
    },
  },
}

messages[0x05ff4400] = {
  name = "BmsSequence_4400",
  extended = true,
  comment = "[probable] A counter the BMS increments once per frame of this message. NOT a clock. CORRECTION. This was recorded as \"BmsAwakeTime_4400\", a fourth 10-second ... (dbc/signals.toml)",
  signals = {
    {
      field = f_bmssequence_4400_sequence,
      first = 0,
      count = 4,
      suffix = " [probable]",
      value = function(tvb) return be(tvb, 0, 32, false) end,
    },
  },
}

messages[0x02ff2602] = {
  name = "AuthNonce_2602",
  extended = true,
  comment = "[probable] Eight bytes of high-entropy data, fresh every time, every 10 s while the bike is awake. Every frame recorded is unique: 1DF37DBD1F0BFC27 ... (dbc/signals.toml)",
  signals = {},
}

messages[0x02472602] = {
  name = "AuthChallengeMeUnlock",
  extended = true,
  comment = "[confirmed] A single frame of eight high-entropy bytes, sent once per MEULK command. Twice recorded, twice different: C2D31EB512687FF3 on 7 September and ... (dbc/signals.toml)",
  signals = {},
}

messages[0x04ff3604] = {
  name = "Unknown_3604",
  extended = true,
  comment = "[hypothesis] The fastest message on the bus at 30 ms, and the most valuable unknown. Not decoded, but enough is now known to rule things out and to say what to ... (dbc/signals.toml)",
  signals = {
    {
      field = f_unknown_3604_analoguea,
      first = 0,
      count = 2,
      suffix = " [hypothesis]",
      value = function(tvb) return be(tvb, 0, 16, false) end,
    },
    {
      field = f_unknown_3604_analogueb,
      first = 2,
      count = 2,
      suffix = " [hypothesis]",
      value = function(tvb) return be(tvb, 16, 16, false) end,
    },
    {
      field = f_unknown_3604_constant200,
      first = 4,
      count = 2,
      suffix = " [hypothesis]",
      value = function(tvb) return be(tvb, 32, 16, false) end,
    },
  },
}

messages[0x03ff1603] = {
  name = "Unknown_1603",
  extended = true,
  comment = "[hypothesis] 105 ms, and constant for a whole session, which is a strange pair. Bytes 0-3 big-endian read as a value very close to the pack voltage: session 1 ... (dbc/signals.toml)",
  signals = {
    {
      field = f_unknown_1603_voltagelike,
      first = 0,
      count = 4,
      suffix = " mV [hypothesis]",
      value = function(tvb) return be(tvb, 0, 32, false) end,
    },
  },
}

messages[0x03ff1000] = {
  name = "Heartbeat_1000",
  extended = true,
  comment = "[probable] A heartbeat. Every 105 ms, payload 0840112200000001. It runs while the bus sleeps, so it is one of the five identifiers a locked bike still sends ... (dbc/signals.toml)",
  signals = {
    {
      field = f_heartbeat_1000_systemready,
      first = 0,
      count = 1,
      suffix = " [probable]",
      value = function(tvb) return be(tvb, 4, 1, false) end,
    },
  },
}

messages[0x1ff8b028] = {
  name = "LockTransition_B028",
  extended = true,
  comment = "[probable] One all-zero frame per lock-state transition. Listed in nodes.md as a constant until the 9 September unlock/lock session; the payload IS constant ... (dbc/signals.toml)",
  signals = {},
}

local function dissect(tvb, pinfo, tree)
  local identifier = can_id()
  if not identifier then
    return false
  end
  local message = messages[identifier.value]
  if message == nil then
    return false
  end
  -- Every identifier on this bus is extended. Declining a standard frame that
  -- happens to collide leaves it to whatever else wants it.
  local extended = can_extended()
  if message.extended and not (extended and extended.value) then
    return false
  end

  pinfo.cols.protocol = "eBike"
  pinfo.cols.info = message.name

  local subtree = tree:add(ebike, tvb(), "Forest ebike: " .. message.name)
  subtree:add(f_message, tvb(), message.name):set_generated()
  subtree:add(tvb(), message.comment)

  for _, signal in ipairs(message.signals) do
    -- A short payload is dissected as far as it goes rather than dropped: an
    -- unexpectedly truncated frame is itself worth seeing.
    if tvb:len() >= signal.first + signal.count then
      local item = subtree:add(
        signal.field,
        tvb(signal.first, signal.count),
        signal.value(tvb)
      )
      if signal.suffix ~= "" then
        item:append_text(signal.suffix)
      end
    end
  end

  return true
end

ebike:register_heuristic("can", dissect)
